# branchName: "${issue.number}-${issue.title}"
branchName: "${issue.number}"
gitSafeReplacementChar: "-"
branches:
  - label: '*'
    prefix: feature/
# branches:
#   - label: feat
#     prefix: feature/
#   - label: bug
#     prefix: bugfix/
#   - label: refactor
#     prefix: refactor/
autoCloseIssue: true
